\c data_wharehouse_dev;

INSERT INTO users02 (first_name , last_name, email, username, phone,
  created_at) VALUES 
  ('Kenti','Johnson','kentijohnson@gmail.com','kjohnson','123456789',NOW()),
  ('James','Madison','jamesmad@gmail.com','jmadison','4041234556',NOW()),
  ('Elizabeth','Montgomery','emonty@gmail.com','lizmont','234123123',NOW());

  INSERT INTO animes02  (char_img, char_name, char_desc, movie, likes_id, created_at) VALUES
  ('https://upload.wikimedia.org/wikipedia/en/2/2b/Sailor_Moon_01.jpg','Sailor Moon','Usagi Tsukino, renamed Serena in the DiC and Cloverway English adaptations and Bunny in the Mixx/Tokyopop adaptation), better known as Sailor Moon, is a Japanese superheroine and the protagonist of the Sailor Moon franchise created by Naoko Takeuchi. She is introduced in chapter No. 1 of the manga, "Usagi – Sailor Moon" (originally published in Japan''s Nakayoshi magazine on December 28, 1991), as a carefree Japanese schoolgirl who can transform into the magical "Guardian of Love and Justice", Sailor Moon. Usagi initially meets Luna, a magical talking black cat who is searching for the Moon Princess. Luna reveals that Usagi is destined to save Earth from the forces of evil and gives her a brooch to transform into Sailor Moon. She asks Usagi to locate the other reincarnated Sailor Guardians, find the princess and protect the "Silver Crystal", an item of immense power. After locating her comrades, Usagi later discovers that she is the reincarnation of the Moon Princess, Princess Serenity and that her former lover, Prince Endymion of Earth has also been reincarnated in the present as the mysterious hero, Tuxedo Mask. As Usagi matures, she becomes a powerful warrior and protects her adopted home planet, Earth, from villains who wish to harm it. Usagi is depicted as usually carefree and cheerful, but with immature tendencies that show themselves when things do not go her way.','Sailor Moon', '{"1","2"}', NOW()),
  ('https://static.wikia.nocookie.net/onepiece/images/6/6d/Monkey_D._Luffy_Anime_Post_Timeskip_Infobox.png/revision/latest?cb=20240306200817','Monkey D. Luffy','also known as "Straw Hat" Luffy[n 2], is a fictional character and the protagonist in the Japanese manga series One Piece created by Eiichiro Oda. Luffy made his debut as a young boy who acquires the properties of rubber after accidentally eating one of the Devil Fruits that belonged to "Red Hair" Shanks. Monkey D. Luffy is the captain of the Straw Hat Pirates, and dreamt of being a pirate since childhood from the influence of his idol and mentor Red-Haired Shanks. At the age of 17, Luffy sets sail from the East Blue Sea to the Grand Line in search of the legendary treasure, One Piece, to succeed Gol D. Roger as "King of the Pirates".','One Piece','{"1"}',NOW()),
  ('https://static.wikia.nocookie.net/dragonball/images/b/ba/Goku_anime_profile.png/revision/latest/scale-to-width-down/1000?cb=20220825041430','Son Goku','A Saiyan raised on Earth and the main protagonist of the Dragon Ball series. He is the second born, as well as youngest son and child of Bardock and Gine, the husband of Chi-Chi, and the father of Gohan and Goten. Originally sent to Earth by his parents as an infant, Kakarot was adopted by Grandpa Gohan and renamed Son Goku. A head injury at an early age altered Goku''s memory, ridding him of his initial destructive nature and allowing him to grow up to become one of Earth''s greatest defenders. Goku constantly strives and trains to be the greatest warrior possible, which has kept the Earth and the universe safe from destruction multiple times.','Dragon Ball','{"1","2","3"}',NOW()),
  ('https://static.wikia.nocookie.net/bakemonogatari1645/images/b/b9/Shinobu.png/revision/latest?cb=20161221045011','Shinobu Oshino','Shinobu Oshino is a mysterious vampire girl who acts as Meme Oshino''s companion in the ruins of Eikou Cram School. Later in the series, she resides in Koyomi Araragi''s shadow during the day. She was formerly a human child princess named Rola (likely meant to be Laura, Lola, or Lora in English, though it may reference the name Acerola) who was cursed into causing anyone in proximity to her to commit suicide. She then took the name of Acerola before meeting a purebred vampire that turned her into a powerful vampire named Kiss-Shot Acerola-Orion Heart-Under-Blade. She now takes the form of an eight-year-old girl with another new name after losing most of her powers.','Bakemonogatari','{"1","2"}',NOW()),
  ('https://upload.wikimedia.org/wikipedia/en/4/46/GintokiSakata.jpg','Gintoki Sakata','Gintoki Sakata is a fictional character in the manga and anime franchise Gintama created by Hideaki Sorachi. Gintoki is the protagonist of the series and his name serves as part of the basis of the series'' title. He is introduced as a former rebel samurai who lives in a fictionalized version of 1860s Japan after being invaded and transformed by aliens. Gintoki once fought in the Joui (rebel) war until a tragic event where he was unable to protect what he was fighting for, leading to him instead establishing "Yorozuya Gin-chan" (万事屋銀ちゃん)" (with Yorozuya (万事屋) literally meaning "worker of 10,000 jobs"), choosing to make a living as a freelancer for hire in Edo. Eventually, Shinpachi Shimura and Kagura choose to stay and work with him, forming a found family. Across the series, more details about Gintoki''s past are revealed leading him to encounter former friends as enemies. As the main character, Gintoki has appeared in most of the episodes of the anime series, as well as in other media related to the franchise, including the film and all of the spin-off video games and original video animations.','Gintama','{"1","3"}',NOW());


-- psql -U postgres -f db/seed.sql
-- as user postgres
-- f file to run
-- file name of file to run